/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_n05;

import javax.swing.JOptionPane;
import Objetos.obj_CalculoMedia;


public class fr_CalculoMedia extends javax.swing.JFrame {

    obj_CalculoMedia  local_CalculoMedia = new obj_CalculoMedia ();
    
    public fr_CalculoMedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lb_Aluno = new javax.swing.JLabel();
        lb_P1 = new javax.swing.JLabel();
        lb_p2 = new javax.swing.JLabel();
        lb_p3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_Aluno = new javax.swing.JTextField();
        tf_P1 = new javax.swing.JTextField();
        tf_P2 = new javax.swing.JTextField();
        tf_P3 = new javax.swing.JTextField();
        tf_At = new javax.swing.JTextField();
        bt_Limpar = new javax.swing.JButton();
        bt_Calcula = new javax.swing.JButton();
        tf_MediaFinal = new javax.swing.JTextField();
        lb_MediaFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculo Média");

        lb_Aluno.setText("Aluno:");

        lb_P1.setText("P1:");

        lb_p2.setText("P2:");

        lb_p3.setText("P3:");

        jLabel5.setText("Atividade:");

        tf_Aluno.setToolTipText("");

        bt_Limpar.setText("Limpar");
        bt_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LimparActionPerformed(evt);
            }
        });

        bt_Calcula.setText("Calcula");
        bt_Calcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CalculaActionPerformed(evt);
            }
        });

        lb_MediaFinal.setText("Média Final:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_Limpar)
                                .addGap(32, 32, 32)
                                .addComponent(bt_Calcula))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_Aluno)
                                    .addComponent(lb_P1)
                                    .addComponent(lb_p2)
                                    .addComponent(lb_p3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_P1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(tf_P2)
                                        .addComponent(tf_P3))
                                    .addComponent(tf_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lb_MediaFinal)
                        .addGap(18, 18, 18)
                        .addComponent(tf_MediaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tf_At, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Aluno)
                    .addComponent(tf_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_P1)
                    .addComponent(tf_P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_p2)
                    .addComponent(tf_P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_p3)
                    .addComponent(tf_P3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_At, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar)
                    .addComponent(bt_Calcula))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_MediaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_MediaFinal))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void bt_LimparActionPerformed(java.awt.event.ActionEvent evt) {                                          
        LimparTela();  
    }                                         

    private void bt_CalculaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if(isCamposPreenchidos ()) {
            
            trataNumericos();
            local_CalculoMedia.setAluno(tf_Aluno.getText().trim());
            
            if (tf_P3.getText().trim().isEmpty()) {
                local_CalculoMedia.CalculoMedia(local_CalculoMedia.getP1(), local_CalculoMedia.getP2(), local_CalculoMedia.getAt());
            } else  {
                local_CalculoMedia.CalculoMedia(local_CalculoMedia.getP1(), local_CalculoMedia.getP2(), local_CalculoMedia.getP3(), local_CalculoMedia.getAt());
            }
            
            tf_MediaFinal.setText(String.valueOf(local_CalculoMedia.getMedia()));
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos", "Erro Campos", JOptionPane.ERROR_MESSAGE);
            
        }
                
        
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_CalculoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_CalculoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_CalculoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_CalculoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_CalculoMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_Calcula;
    private javax.swing.JButton bt_Limpar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb_Aluno;
    private javax.swing.JLabel lb_MediaFinal;
    private javax.swing.JLabel lb_P1;
    private javax.swing.JLabel lb_p2;
    private javax.swing.JLabel lb_p3;
    private javax.swing.JTextField tf_Aluno;
    private javax.swing.JTextField tf_At;
    private javax.swing.JTextField tf_MediaFinal;
    private javax.swing.JTextField tf_P1;
    private javax.swing.JTextField tf_P2;
    private javax.swing.JTextField tf_P3;
    // End of variables declaration                   

public void LimparTela() {
    tf_Aluno.setText(null);
    tf_At.setText(null);
    tf_MediaFinal.setText(null);
    tf_P1.setText(null);
    tf_P2.setText(null);
    tf_P3.setText(null);
}


public boolean isCamposPreenchidos () {
    boolean saida=true;
    
    if ((tf_Aluno.getText().trim().isEmpty())||
        (tf_At.getText().trim().isEmpty())||
        (tf_P1.getText().trim().isEmpty())||
        (tf_P2.getText().trim().isEmpty())
       ) 
    {
        saida=false;
    }
    
    return saida;
}


public void trataNumericos() {
    
    try {
        
        local_CalculoMedia.setP1(Double.parseDouble(tf_P1.getText().trim()));
        local_CalculoMedia.setP2(Double.parseDouble(tf_P2.getText().trim()));
        local_CalculoMedia.setAt(Double.parseDouble(tf_At.getText().trim()));
        
        if (!tf_P3.getText().trim().isEmpty()) {
            local_CalculoMedia.setP3(Double.parseDouble(tf_P3.getText().trim()));
        }
        
    } catch (NumberFormatException erro) {
        JOptionPane.showMessageDialog(null, "Notas devem ser Numéricas. \n Use o ponto decimal, não vírgulas", "Erro Numéricos", JOptionPane.ERROR_MESSAGE );
    }
    
}


} ////////////////////////////////fim da classe
