/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_n05;

/**
 *
 * @author slodd
 */
public class fr_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form fr_MenuPrincipal
     */
    public fr_MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mn_Senha = new javax.swing.JMenu();
        imn_ValidarSenha = new javax.swing.JMenuItem();
        imn_ValidaSenhaSup = new javax.swing.JMenuItem();
        mn_Cadastro = new javax.swing.JMenu();
        imn_CadastroAluno = new javax.swing.JMenuItem();
        imn_CadAlunoIntercambio = new javax.swing.JMenuItem();
        mn_Transacoes = new javax.swing.JMenu();
        imn_CalculoMedia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        mn_Senha.setText("Senha");

        imn_ValidarSenha.setText("ValidaSenha");
        imn_ValidarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ValidarSenhaActionPerformed(evt);
            }
        });
        mn_Senha.add(imn_ValidarSenha);

        imn_ValidaSenhaSup.setText("Valida Senha Supervisor");
        imn_ValidaSenhaSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ValidaSenhaSupActionPerformed(evt);
            }
        });
        mn_Senha.add(imn_ValidaSenhaSup);

        jMenuBar1.add(mn_Senha);

        mn_Cadastro.setText("Cadastros");

        imn_CadastroAluno.setText("Cadastro Alunos");
        imn_CadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_CadastroAlunoActionPerformed(evt);
            }
        });
        mn_Cadastro.add(imn_CadastroAluno);

        imn_CadAlunoIntercambio.setText("Cadastro Aluno Intercambio");
        imn_CadAlunoIntercambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_CadAlunoIntercambioActionPerformed(evt);
            }
        });
        mn_Cadastro.add(imn_CadAlunoIntercambio);

        jMenuBar1.add(mn_Cadastro);

        mn_Transacoes.setText("Transações");

        imn_CalculoMedia.setText("Calculo Média");
        imn_CalculoMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_CalculoMediaActionPerformed(evt);
            }
        });
        mn_Transacoes.add(imn_CalculoMedia);

        jMenuBar1.add(mn_Transacoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void imn_ValidarSenhaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        fr_ValidaSenha  localValidaSenha = new fr_ValidaSenha ();
        localValidaSenha.setVisible(true);
    }                                                

    private void imn_CadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        fr_TelaCadastro  localCadastro = new fr_TelaCadastro ();
        localCadastro.setVisible(true);
    }                                                 

    private void imn_ValidaSenhaSupActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        fr_ValidaSenha_sup  localValidaSenha_sup = new fr_ValidaSenha_sup ();
        localValidaSenha_sup.setVisible(true);        
    }                                                  

    private void imn_CalculoMediaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        fr_CalculoMedia local_CalculoMedia =  new fr_CalculoMedia ();
        local_CalculoMedia.setVisible(true);
    }                                                

    private void imn_CadAlunoIntercambioActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        fr_TelaCadastro_Intercambio  local_CadastroInt = new fr_TelaCadastro_Intercambio ();
        local_CadastroInt.setVisible(true);
    }                                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem imn_CadAlunoIntercambio;
    private javax.swing.JMenuItem imn_CadastroAluno;
    private javax.swing.JMenuItem imn_CalculoMedia;
    private javax.swing.JMenuItem imn_ValidaSenhaSup;
    private javax.swing.JMenuItem imn_ValidarSenha;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mn_Cadastro;
    private javax.swing.JMenu mn_Senha;
    private javax.swing.JMenu mn_Transacoes;
    // End of variables declaration                   
}
